;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	query-replace
	sp-backward-sexp
	sp-backward-up-sexp
	sp-forward-sexp
	sp-up-sexp
	))

(setq mc/cmds-to-run-once
      '(
	consult-buffer
	reposition-window
	occur
	consult-line
	))
