;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	LaTeX-insert-left-brace
	cua-paste
	end-of-buffer
	ignore-preserving-kill-region
	org-beginning-of-line
	org-end-of-line
	org-self-insert-command
	query-replace
	sp-backward-sexp
	sp-backward-up-sexp
	sp-forward-sexp
	sp-up-sexp
	))

(setq mc/cmds-to-run-once
      '(
	consult-buffer
	consult-line
	lsp-ui-doc--handle-mouse-movement
	occur
	org-edit-src-save
	python-shell-send-buffer
	reposition-window
	))
